# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release with goreleaser

on:
  push:
    tags:
      - v*
      
permissions: write-all # Necessary for the generate-build-provenance action with containers

jobs:

  build:


    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: 1
          fetch-depth: 1
      - name: Release with goreleaser
        uses: goreleaser/goreleaser-action@v5
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          version: latest
          args: release --clean
        id: goreleaser